# ---------------------------------------------------------------
# Global
# ---------------------------------------------------------------

# default image
image: node:14-slim

stages:
  - environment
  - build
  - alt_build
#  - test
  - release
  - docker
  - docs

# ---------------------------------------------------------------
# Global variables
# ---------------------------------------------------------------

variables:
  DOCKER_IMAGE_REGISTRY: gitlab-registry.ifremer.fr/ifremer-commons/docker/images/
  CI_BUILD_IMAGE: $CI_REGISTRY_IMAGE/build:develop
  BUILD_CACHE_DIR: /tmp/.build-cache
  BUILD_ENVIRONMENT: prod
  DOCKER_BUILDKIT: 1
  ARTIFACT_ZIP_FILES: ${OUTPUT_DIR}/${CI_PROJECT_NAME}-*.zip
  ENV_FILE: variables.env

# ---------------------------------------------------------------
# Jobs templates
# ---------------------------------------------------------------
.configure-git-template: &git-setup
  before_script:
    - echo "fetch origin"
    - git remote set-url origin "https://gitlab+access-token:${CI_ACCESS_TOKEN}@gitlab.ifremer.fr/${CI_PROJECT_PATH}.git"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git fetch origin
  tags: [sih_public_runner]

.docker:
  image: docker:latest
  tags: [sih_public_runner]
  services:
    - docker:dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  after_script:
    - docker logout ${CI_REGISTRY}
  allow_failure: false

# ---------------------------------------------------------------
# Environment jobs : Create docker image for builds/release, this
# offers possibility to cache project dependencies so we don't
# have to download them every time.
# ---------------------------------------------------------------
build:env:
  extends: .docker
  stage: environment
  script:
    # Create the target directory
    - mkdir -p target/docker
    - cp -rf scripts/docker/build/* target/docker
    # Build and push the CI image
    - docker build --cache-from ${CI_BUILD_IMAGE} -t ${CI_BUILD_IMAGE} --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg="CACHE_DIR=${BUILD_CACHE_DIR}" --build-arg="IMAGE_REGISTRY=${DOCKER_IMAGE_REGISTRY}" -f target/docker/Dockerfile .
    - docker push ${CI_BUILD_IMAGE}
  except:
    - tags
    - master

# ---------------------------------------------------------------
# Build jobs
# ---------------------------------------------------------------
.build:
  stage: build
  tags: [sih_public_runner]
  needs: ["build:env"]
  script:
    # Show version
    - ng version
    - npm version
    # Build
    - npm run build.${BUILD_ENVIRONMENT}
  after_script:
    # Remember version
    - APP_VERSION=$(node -e "console.log(require('./package.json').version)")
    - echo "APP_VERSION=${APP_VERSION}" > ${ENV_FILE}
  artifacts:
    paths:
      - www
    reports:
      dotenv: ${ENV_FILE}
    expire_in: 72 hours

build:
  extends: .build
  image: ${CI_BUILD_IMAGE}
  before_script:
    # Get project dependencies
    - ls -artl ${BUILD_CACHE_DIR}
    - cp -R ${BUILD_CACHE_DIR}/node_modules .
  variables:
    BUILD_ENVIRONMENT: dev
  only:
    - develop

build:feature:
  extends: .build
  image: ${CI_BUILD_IMAGE}
  only:
    - /^feature\/.*/
  when: manual

failsafe-build:
  extends: .build
  stage: alt_build
  when: on_failure
  before_script:
    # Install global dependencies
    - npm install -g @ionic/cli@6.19.1 @angular/cli@11.2.19
    # Update project dependencies
    - npm install
  variables:
    BUILD_ENVIRONMENT: dev
  only:
    - develop
    - /^feature\/.*/

# ---------------------------------------------------------------
# Release jobs
# ---------------------------------------------------------------
.release:
  <<: *git-setup
  stage: release
  script:
      - if [[ "_${RELEASE_VERSION}" == "_" ]]; then exit 1; fi
      - echo "--- Release in progress"
      - git checkout -b release/${RELEASE_VERSION}
      - echo "--- Manage app version"
      - 'currentAndroid=`grep -oP "android-versionCode=\"[0-9]+\"" config.xml | grep -oP "\d+"`'
      - 'IFS="."'
      - 'read -ra SPLITED_VERSION <<< "${RELEASE_VERSION}"'
      - 'IFS="-"'
      - 'read -ra SPLITED_PATCH <<< "${SPLITED_VERSION[2]}"'
      - 'major2d=$(printf %02d ${SPLITED_VERSION[0]}) ; minor2d=$(printf %02d ${SPLITED_VERSION[1]}) ; patch2d=$(printf %02d ${SPLITED_PATCH[0]})'
      - 'androidVersion=$major2d$minor2d$patch2d'
      - 'current=`grep -oP "version\": \"\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?" package.json | grep -m 1 -oP "\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?"`'
      - 'sed -i "s/version\": \"$current\"/version\": \"${RELEASE_VERSION}\"/g" package.json'
      - 'currentConfigXmlVersion=`grep -oP "version=\"\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?\"" config.xml | grep -oP "\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?"`'
      - 'sed -i "s/ version=\"$currentConfigXmlVersion\"/ version=\"${RELEASE_VERSION}\"/g" config.xml'
      - 'sed -i "s/ android-versionCode=\"$currentAndroid\"/ android-versionCode=\"$androidVersion\"/g" config.xml'
      - 'currentManifestJsonVersion=`grep -oP "version\": \"\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?\"" src/assets/manifest.json | grep -oP "\d+.\d+.\d+(-(alpha|beta|rc)[0-9]+)?"`'
      - 'sed -i "s/version\": \"$currentManifestJsonVersion\"/version\": \"${RELEASE_VERSION}\"/g" src/assets/manifest.json'
      - 'sed -i "s/echo \".*\" #lastest/echo \"${RELEASE_VERSION}\" #lastest/g" install.sh'
      # Copy cached dependencies and build
      - ls -artl "${BUILD_CACHE_DIR}"
      - cp -R "${BUILD_CACHE_DIR}/node_modules" .
      # Show version
      - ng version
      - npm version
      # Build
      - export NODE_OPTIONS=--max-old-space-size=4096
      - npm run build.prod
      # Git process for release (ISO gitflow)
      - git add .
      - git commit -m "Prepare release ${RELEASE_VERSION}"
      - git checkout master
      - git merge --no-ff --no-edit -m "Release ${RELEASE_VERSION}" "release/${RELEASE_VERSION}"
      - git tag -a "${RELEASE_VERSION}" -m "${RELEASE_VERSION}"
      - git checkout develop
      - git merge --no-ff --no-edit -m "[skip ci] Release ${RELEASE_VERSION}" "release/${RELEASE_VERSION}"
      - git push origin develop
      - git push origin master
      - git push --tags
      - git branch -D "release/${RELEASE_VERSION}"
  after_script:
    # Remember version
    - APP_VERSION=$(node -e "console.log(require('./package.json').version)")
    - echo "APP_VERSION=${APP_VERSION}" > ${ENV_FILE}
    # Zip output
    - fileName=sumaris-app-${APP_VERSION}.zip
    - currentDir=$(pwd)
    - mkdir -p ${currentDir}/dist
    - zipFile=${currentDir}/dist/${fileName}
    - if [[ -f "${zipFile}" ]]; then rm "${zipFile}"; fi
    - cd www || exit 1
    - if ! zip -q -r "${zipFile}" . ; then echo "Cannot create the archive for the web artifact"; exit 1; fi
    - cd ..
    - targetUrl="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/sumaris-app/${APP_VERSION}/${fileName}"
    - echo "Deploy to gitlab generic package :"
    - echo " File= ${zipFile}"
    - echo " Url= ${targetUrl}"
    - 'if ! curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "${zipFile}" "${targetUrl}"; then exit 1; fi'
  artifacts:
    paths:
      - www
    reports:
      dotenv: ${ENV_FILE}
    expire_in: 24 hours
  allow_failure: false
  only:
    - develop
  when: manual

release:
    extends: .release
    image: ${CI_BUILD_IMAGE}
    needs: [build]

failsafe-release:
    extends: .release
    needs: [failsafe-build]

release:tags:
  <<: *git-setup
  image: ${CI_BUILD_IMAGE}
  stage: release
  script:
    - RELEASE_VERSION=$(node -e "console.log(require('./package.json').version)")
    - echo "--- Release in progress"
    - git checkout -b release/${RELEASE_VERSION}
    # Copy cached dependencies and build
    - ls -artl /tmp/.build-cache
    - cp -R /tmp/.build-cache/node_modules .
    # Show version
    - ng version
    - npm version
    # Build
    - export NODE_OPTIONS=--max-old-space-size=4096
    - npm run build.prod
  after_script:
    # Remember version
    - APP_VERSION=$(node -e "console.log(require('./package.json').version)")
    - echo "APP_VERSION=${APP_VERSION}" > ${ENV_FILE}
  artifacts:
    paths:
      - www
    reports:
      dotenv: ${ENV_FILE}
    expire_in: 24 hours
  allow_failure: false
  when: manual
  only:
    - tags

gitlab-release:
    stage: release
    tags: [sih_public_runner]
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    script:
        - echo "running release for ${CI_COMMIT_TAG}"
    release:
        name: "Release ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        description: "Created using the release-cli $EXTRA_DESCRIPTION"
        tag_name: "${CI_COMMIT_TAG}"
        ref: "${CI_COMMIT_TAG}"
    only:
        - tags

# ---------------------------------------------------------------
# Docker jobs
# ---------------------------------------------------------------
.docker-build:
  extends: .docker
  stage: docker
  script:
    # Create the target directory
    - mkdir -p target/docker
    - cp -rf scripts/docker/run/* target/docker
    # Build docker image
    - docker pull ${CI_REGISTRY_IMAGE}:${IMAGE_TAG} || true
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:${IMAGE_TAG} --pull -t ${CI_REGISTRY_IMAGE}:${IMAGE_TAG} --build-arg="HTML=www" --build-arg="NGINX_CONF=target/docker/site.conf" -f target/docker/Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}

docker:develop:
  extends: .docker-build
  variables:
    IMAGE_TAG: develop
  needs: [build]
  only:
    - develop

docker:feature:
  extends: .docker-build
  needs: [build:feature]
  variables:
    IMAGE_TAG: feature
  only:
    - /^feature\/.*/
  when: manual

docker:release:
  extends: .docker-build
  variables:
    IMAGE_TAG: ${APP_VERSION}
  needs: [release]
  only:
    - develop

docker:release:tags:
  extends: .docker-build
  variables:
    IMAGE_TAG: ${APP_VERSION}
  needs: [release:tags]
  only:
    - tags

# ---------------------------------------------------------------
# Docs jobs
# ---------------------------------------------------------------

pages:
  stage: docs
  tags: [sih_public_runner]
  image: python:3.7-alpine
  before_script:
    - apk --update --upgrade add gcc musl-dev jpeg-dev zlib-dev libffi-dev cairo-dev pango-dev gdk-pixbuf-dev
    - pip install --upgrade pip
    - pip install --upgrade mkdocs
    - pip install --upgrade mkdocs-pdf-export-plugin==0.5.5
  script:
    - mkdocs -v build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - develop
  when: manual

